# Generated by Django 4.2.5 on 2023-09-06 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item_db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('auction_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Auction ID')),
                ('bid', models.PositiveIntegerField(verbose_name='Bid Amount')),
                ('buyout', models.PositiveIntegerField(verbose_name='Buyout Amount')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('time_left', models.CharField(max_length=50, verbose_name='Time Left')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_db.item', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Auction',
                'verbose_name_plural': 'Auctions',
                'ordering': ['-timestamp', 'auction_id'],
            },
        ),
    ]
