# Generated by Django 4.2.5 on 2023-09-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemId', models.IntegerField(primary_key=True, serialize=False, verbose_name='Item ID')),
                ('name', models.CharField(max_length=200, verbose_name='Item Name')),
                ('icon', models.CharField(max_length=100, verbose_name='Icon Name')),
                ('icon_image', models.ImageField(upload_to='icon_images/', verbose_name='Icon Image')),
                ('item_class', models.CharField(blank=True, max_length=100, null=True, verbose_name='Class')),
                ('subclass', models.CharField(blank=True, max_length=100, null=True, verbose_name='Subclass')),
                ('sellPrice', models.PositiveIntegerField(blank=True, null=True, verbose_name='Sell Price')),
                ('quality', models.CharField(blank=True, max_length=100, null=True, verbose_name='Quality')),
                ('itemLevel', models.PositiveIntegerField(blank=True, null=True, verbose_name='Item Level')),
                ('requiredLevel', models.PositiveIntegerField(blank=True, null=True, verbose_name='Required Level')),
                ('slot', models.CharField(blank=True, max_length=50, null=True, verbose_name='Slot')),
                ('itemLink', models.TextField(blank=True, null=True, verbose_name='Item Link')),
                ('vendorPrice', models.PositiveIntegerField(blank=True, null=True, verbose_name='Vendor Price')),
                ('contentPhase', models.PositiveIntegerField(blank=True, null=True, verbose_name='Content Phase')),
                ('uniqueName', models.SlugField(blank=True, null=True, verbose_name='Unique Name')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
    ]
