# Generated by Django 4.2.5 on 2023-09-06 21:58

from django.db import migrations, models
import item_db.models


class Migration(migrations.Migration):

    dependencies = [
        ('item_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='icon_image',
            field=models.ImageField(upload_to=item_db.models.item_icon_image_path, verbose_name='Icon Image'),
        ),
    ]
